### ISSUE TITLE
How does svg-jar use svgo

### ISSUE THREAD

**Issue by eramod** [voltidev/ember-svg-jar#147]
#### Describe your question
I recently realized that svg-jar uses svgo for optimization. Before this, I would run new SVGs through svgo on the command line as their README says to do. This resulted in smaller files and all the svgo plugin rules being applied. However, when I wanted to test how svg-jar uses svgo, I tried flipping one of the plugins (removeViewbox) but when I looked at the SVG in the DOM it hadn't applied the rule and my file stayed the same size. Does svg-jar optimize SVGs at buildtime? If not, how does it work?  

For reference, this is the configuration I used to test it out, and I was using an SVG in the icons folder and invoking it with the helper as {{svg-jar 'iconName'}}. When I looked at the SVG in the DOM it still had a viewBox. If I set the removeViewbox to true, shouldn't svg-jar remove the viewBox property in the DOM?

```svgJar: {
      strategy: ['symbol', 'inline'],

      symbol: {
        includeLoader: env !== 'test',
        sourceDirs: ['public/images/symbols']
      },

      inline: {
        sourceDirs: ['public/images/icons'],

        optimizer : {
          plugins: [
            { removeViewbox: true }
          ]
        }
      }
    }```

#### Search tags, topics

<!-- Help others find this and upvote it. -->
<!-- Add meaningful tags for search engines. -->
<!-- #ember-addon #svg #... -->

**Comment by ivanvotti** [comment]
It looks like a bug. I'll check it soon.

**Comment by eramod** [comment]
Could you tell me how it's supposed to work? Should it modify my actual SVG files or does it only run svgo on them at build time?

**Comment by ivanvotti** [comment]
It only applies SVGO plugins at build time and won't modify your source files.
