### ISSUE TITLE
How can I change color of an icon??

### ISSUE THREAD

**Issue by AravinthAro** [voltidev/ember-svg-jar#169]
This is should be very simple I guess. For single tone icons I need to change the color of the icons via helper or overwrite styles. I tried both neither worked for me. Is something else I'm doing wrong?? 

### Configuration
```js
 svgJar: {
      strategy: ['symbol', 'inline'],
      sourceDirs: ['tests/dummy/public']
    }
```

### Helper
```html
{{svg-jar "#27" fill="#00f"}}
<br>
{{svg-jar "27" fill="#00f"}}
```
Please tell me how to change an icon's color?? Thanks in advance.

**Comment by fpauser** [comment]
You could do the following¹:

_Plain handlebars_
```hbs
<span style={{style color="red" fill="currentColor"}}>
  {{svg-jar "whatever-icon"}}
</span>
```

You could also wrap this in a component:

_CustomIcon component template_
```hbs
<span style={{style color=(if @color @color "inherit") fill="currentColor"}} ...attributes>
  {{svg-jar @icon}}
</span>
```

And use it like so:
```hbs
<CustomIcon @color="red" @icon="whatevericon" />
```

¹ Using the `style` modifier from https://github.com/jelhan/ember-style-modifier
