### ISSUE TITLE
2.3.4 works in Ember 4.1 

### ISSUE THREAD

**Issue by mydea** [voltidev/ember-svg-jar#212]
Based on the comment in https://github.com/ivanvotti/ember-svg-jar/blob/master/CHANGELOG.md#v234, just letting you know that this seems to be working just fine for me in our app on Ember 4.1 & embroider.

We are using the `inline` strategy, if that makes any difference.

**Comment by jherdman** [comment]
Thank you for following up! With any luck that means I'm seeing some test-only fails.

**Comment by bertdeblock** [comment]
Works for us as well on `4.1`, no Embroider here atm though.

**Comment by bertdeblock** [comment]
I am seeing the following warning when using Embroider:

```
WARNING in ./helpers/svg-jar.js 8:15-58
Module not found: Error: Can't resolve 'ember-svg-jar/inlined' in '$TMPDIR/embroider/9437f6/helpers'
```

**Comment by nightire** [comment]
@bertdeblock Hello, I'm seeing the same error with embroider, have you fix this error yet?

**Comment by nightire** [comment]
@evoactivity v2.6.0 with a brand new ember app, here's the warning details:

```
WARNING in ../rewritten-packages/ember-svg-jar.dd3ffac0/node_modules/ember-svg-jar/helpers/svg-jar.js 12:17-49
Module not found: Error: Can't resolve '../inlined' in '/PROJECT_PATH/node_modules/.embroider/rewritten-packages/ember-svg-jar.dd3ffac0/node_modules/ember-svg-jar/helpers'
@ ../rewritten-packages/ember-svg-jar.dd3ffac0/node_modules/ember-svg-jar/_app_/helpers/svg-jar.js 1:0-64 1:0-64 1:0-64
@ ./templates/application.hbs 4:0-58 24:49-56
```

I can filter out this warning with webpack plugins, it's just annoy a bit
