### ISSUE TITLE
Make Embroider Optimized Scenario Green

### ISSUE THREAD

**Issue by jherdman** [voltidev/ember-svg-jar#230]
Help please!

**Comment by evoactivity** [comment]
2.3.4 does work with embroider
2.4.0 and 2.4.1 do not work with embroider

If I overwrite the content of `app/helpers/svg-jar.js` with `addon/helpers/svg-jar.js` then it works.
The `require` does not work in `addon/helpers/svg-jar.js`, but it does in `app/helpers/svg-jar.js`.

Maybe @ef4 could shed some light on that behavior?
