### ISSUE TITLE
2.4.0 broken

### ISSUE THREAD

**Issue by evoactivity** [voltidev/ember-svg-jar#233]
I tried updating my app and none of my icons work and the asset viewer no longer loads. 

I don't know why yet.

At runtime I am warned `ember-svg-jar: Missing inline SVG for icon-name`.
There doesn't seem to be any packaged JS for the asset viewer?

edit: 
I wonder if it's down to embroider? Since the errors in the failing embroider-optimised scenario seem similar. Just don't know why 2.3.4 works but not 2.40.

**Comment by bertdeblock** [comment]
The `/public/static` folder is missing in `v2.4.0`.
