### ISSUE TITLE
How to use our custom svg defs tag id instead of system generated

### ISSUE THREAD

**Issue by luxman-arumugam** [voltidev/ember-svg-jar#96]
`<defs>`
`<path id="a" d="M0 .167h108.397v92.212H0z"></path>`
`<path id="c" d="M0 .167h108.397v18.156H0z"></path>`
`</defs>`
In the above code, `a` and `c` id's are system generated. But I need my own id's. Help me to achieve this.

**Comment by drouhard** [comment]
The minification of those ids happens with svgo's `cleanupIDs` plugin. You can disable it like this in your `ember-cli-build.js` config:

```
svgJar: {
  optimizer: {
    plugins: [
      {
        cleanupIDs: false
      }
    ]
  }
}
```
